config/routes.rb
VoteSquared::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :users do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
    resources :follows
    resources :voter_ratings
  end

  resources :politicians do
    resources :watches
    resources :voter_ratings do
      resources :votes
    end
  end

  resources :omniauth_callbacks, :devise

  match '/about/community' => 'about#community', via: [:get]
  match '/about/funding' => 'about#funding', via: [:get]
  match '/about/democratic_antipatterns' => 'about#democratic_antipatterns', via: [:get]
  match '/users/:id/edit', to: 'users#update_custom', via: [:patch]
  match '/politicians/:politician_id/voter_ratings/:id/edit', to: 'voter_ratings#update', via: [:patch]

  root 'welcome#index'
end

app/models/voter_rating.rb
# Model to store ratings from users.
class VoterRating
  include MongoMapper::Document
  include RatingsHtml

  belongs_to :politician

  many :votes

  attr_accessible :voter, :rating

  key :rating, Integer
  key :pros, String
  key :cons, String
  key :voter, Boolean, default: false
  key :voted_for, Boolean, default: false
  key :promised, String
  key :achieved, String
  key :user_id, ObjectId

  # For backwards compatibility with records that have no last edit value this is being left out for now.
  #   We might not ever want to re-add it!
  # validates_associated :politician

  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than: 6 },
                     presence: true, length: { maximum: 1 }

  def rating_html
    html = "<table><td valign=center><b class='rating'>" + @rating.to_s + '</b></td><td> ' + rating_hearts_html(@rating, false)
    html += '</td></table>'
    html.html_safe
  end

  def user_display
    user_value('display')
  end

  def user_name
    user_value('name')
  end

  def user_value(field)
    @user = User.find(@user_id)

    if defined?(@user_id) && ! @user.nil?
      if field == 'name'
        return @user.name
      elsif field == 'display'
        return @user.display
      end
    else
      return 'Deleted User'
    end
  end

  def politician_link
    @politician = Politician.find(@politician_id)
    "<a href=/politicians/#{politician_id}>#{@politician.first_name} #{@politician.last_name}</a>"
  end

  def total_votes
    total_not_useful = 0
    votes.each do |vote|
      total_not_useful += 1 unless vote.useful
    end

    votes.count - total_not_useful
  end
end

app/controllers/voter_ratings_controller.rb
class VoterRatingsController < ApplicationController
  def create
    @politician = Politician.find(params[:politician_id])
    @voter_rating = @politician.voter_ratings.create(voter_rating_params)
    # There has to be a better way to get the data from params:
    @voter_rating.user_id = current_user.id
    file_common_fields

    current_user.add_points(5)
    flash[:notice] = "Thank you, you've earned 5 points!"

    @voter_rating.save
    recipients = []
    @politician.watches.each do |watch|
      send_mail(watch.watcher_id)
      recipients += [watch.watcher_id]
    end
    current_user.follows.each do |follow|
      send_mail(follow.follower_id) unless recipients.include?(follow.follower_id)
    end
    redirect_to politician_path(@politician)
  end

  def send_mail(user_id)
    user = User.find(user_id)
    unless user.unsubscribe_all
      UserMailer.watched_politician_new_rating(@politician, @voter_rating, user, current_user).deliver
    end
  end

  def destroy
    @politician = Politician.find(params[:politician_id])
    @voter_rating = @politician.voter_ratings.find(params[:id])
    @voter_rating.destroy
    current_user.add_points(-5)
    redirect_to politician_path(@politician)
  end

  def edit
    @politician = Politician.find(params[:politician_id])
    @voter_rating = @politician.voter_ratings.find(params[:id])
  end

  def update
    @politician = Politician.find(params[:politician_id])
    @voter_rating = @politician.voter_ratings.find(params[:id])

    if @voter_rating.update_attributes(voter_rating_params)
      file_common_fields

      @voter_rating.save
      redirect_to @politician
    else
      render 'edit'
    end
  end

  # Private members

  private

  def file_common_fields
    @voter_rating.pros = voter_rating_params['pros']
    @voter_rating.cons = voter_rating_params['cons']
    @voter_rating.voter = voter_rating_params['voter']
    @voter_rating.voted_for = voter_rating_params['voted_for']
    @voter_rating.promised = voter_rating_params['promised']
    @voter_rating.achieved = voter_rating_params['achieved']
  end

  def voter_rating_params
    params.require(:voter_rating).permit(:user_id, :rating, :pros, :cons, :voter, :voted_for, :promised, :achieved)
  end
end

app/helpers/voter_ratings_helper.rb
module VoterRatingsHelper
end

app/views/voter_ratings/_show.html.erb
<% has_rating = false %>
<h2>Ratings</h2>
<% sorted_voters = @politician.voter_ratings.sort! { |a,b| b.total_votes <=> a.total_votes } %>
<% sorted_voters.each do |voter_rating| %> 
  <hr>
  <table class='hreview'>
  <span class="item" style='visibility:hidden'><span class="fn"><%= @politician.full_name %></span></span>
    <td>
      <%= link_to(raw("<img src=/UpVote.png alt='useful'>"), politician_voter_rating_votes_path(@politician,voter_rating), :method => :up_vote) %>
      <center><strong><%= voter_rating.total_votes %></strong></center>
      <%= link_to(raw("<img src=/DownVote.png alt='not useful'>"), politician_voter_rating_votes_path(@politician,voter_rating), :method => :down_vote) %>
    </td>
    <td>
      
      <%= render "voter_ratings/show_rating_detail", :voter_rating => voter_rating %>
  
      <% if user_signed_in? && current_user.id == voter_rating.user_id %>
        <% has_rating = true %>
        <table cellspacing=10><tr>
          <td>
            <%= link_to 'Delete Rating', [voter_rating.politician, voter_rating], 
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
          </td><td>
            <%= link_to 'Edit Rating', edit_politician_voter_rating_path(voter_rating.politician, voter_rating) %>
          </td><br>
        </table>
      <% end %>
    </td>
  </table>
<% end %>
<% if user_signed_in? && ! has_rating %>
  <script>document.getElementById('rating_link').style.display = 'inline'</script>
  <h2><a name="add_rating">Add a rating:</a></h2>
  <%= form_for([@politician, @politician.voter_ratings.build]) do |f| %>
    <p>
      <%= f.label :rating %><br>
      <%= f.select :rating, [['1 heart',1], ['2 hearts',2], ['3 hearts',3], ['4 hearts',4], ['5 hearts',5]]  %>
    </p>
    <p>
      <%= f.label :pros %> (What do you like about them?)<br>
      <%= f.text_area :pros %>
    </p>
    <p>
      <%= f.label :cons %> (How could they improve?)<br>
      <%= f.text_area :cons %>
    </p>
    <p>
      Are you a voter in this politicians district? (ie: can you or have you been able to vote for this person?)<br>
      Yes <%= f.radio_button :voter, true, checked:true, :onclick => "document.getElementById('voter_section').style.display = 'inline'" %>
      No <%= f.radio_button :voter, false , :onclick => "document.getElementById('voter_section').style.display = 'none'"%>
    </p>
    <div id='voter_section' style="display:none">
      <p>
        Have you voted for them?<br>
        Yes <%= f.radio_button :voted_for, true %>
        No <%= f.radio_button :voted_for, false, checked:true %>
      </p>
      <p>
        What have they promised?<br>
        <%= f.text_area :promised %>
      </p>
      <p>
        What have they achieved?<br>
        <%= f.text_area :achieved %>
      </p>
    </div>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>

app/views/voter_ratings/_show_rating_detail.html.erb
<%= voter_rating.rating_html %>
<span class='description'>
  <p>
    <strong>Pros:</strong>
    <%= voter_rating.pros %>
  </p>
  <p>
    <strong>Cons:</strong>
    <%= voter_rating.cons %>
  </p>
</span>

<% if voter_rating.voter %>
  <strong>This rating is from a voter who was promised:</strong><br>
    <%= voter_rating.promised %>
  </p>
  <p>
    <strong>Felt the politician achieved:</strong><br>
    <%= voter_rating.achieved %>
  </p>
<% end %>

<span class='reviewer'><%= voter_rating.user_display.html_safe %></span>

app/views/voter_ratings/edit.html.erb
<%= render "shared/top" %>
  <%= form_for [@politician, @politician.voter_ratings.build], method: :patch, :url => edit_politician_voter_rating_path do |f| %>
  
    <p>
      <%= f.label :rating %><br>
      <%= f.select :rating, [['1 heart',1], ['2 hearts',2], ['3 hearts',3], ['4 hearts',4], ['5 hearts',5]], :selected => @voter_rating.rating %>
    </p>
    <p>
      <%= f.label :pros %> (What do you like about them?)<br>
      <%= f.text_area :pros, :value => @voter_rating.pros %>
    </p>
    <p>
      <%= f.label :cons %> (How could they improve?)<br>
      <%= f.text_area :cons, :value => @voter_rating.cons %>
    </p>
    <p>
      Are you a voter in this politicians district? (ie: can you or have you been able to vote for this person?)<br>
      Yes <%= f.radio_button :voter, ! @voter_rating.voter, :onclick => "document.getElementById('voter_section').style.display = 'inline'" %>
      No <%= f.radio_button :voter, @voter_rating.voter, :onclick => "document.getElementById('voter_section').style.display = 'none'"%>
    </p>
    <p>
      Have you voted for them?<br>
      Yes <%= f.radio_button :voted_for, ! @voter_rating.voted_for %>
      No <%= f.radio_button :voted_for, @voter_rating.voted_for %>
    </p>
    <p>
      What have they promised?<br>
      <%= f.text_area :promised, :value => @voter_rating.promised %>
    </p>
    <p>
      What have they achieved?<br>
      <%= f.text_area :achieved, :value => @voter_rating.achieved %>
    </p>
    <p>
      <%= f.submit "Update Rating" %>
    </p>
  <% end %>
<%= render "shared/bottom" %>