config/routes.rb
VoteSquared::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :users do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
    resources :follows
    resources :voter_ratings
  end

  resources :politicians do
    resources :watches
    resources :voter_ratings do
      resources :votes
    end
  end

  resources :omniauth_callbacks, :devise

  match '/about/community' => 'about#community', via: [:get]
  match '/about/funding' => 'about#funding', via: [:get]
  match '/about/democratic_antipatterns' => 'about#democratic_antipatterns', via: [:get]
  match '/users/:id/edit', to: 'users#update_custom', via: [:patch]
  match '/politicians/:politician_id/voter_ratings/:id/edit', to: 'voter_ratings#update', via: [:patch]

  root 'welcome#index'
end

app/models/user.rb
# Model to store users
class User
  include MongoMapper::Document
  plugin MongoMapper::Plugins::IdentityMap

  many :voter_ratings
  many :votes
  many :watches
  many :follows

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:facebook]

  attr_accessible :email, :name, :encrypted_password, :confirmed_at, :points

  key :name, String
  key :email, String
  key :password, String
  key :image, String
  key :encrypted_password, String
  key :confirmed_at, Time
  key :confirmation_sent_at, Date
  key :confirmation_token, String
  key :current_sign_in_at, Time
  key :last_sign_in_at, Time
  key :current_sign_in_ip, String
  key :last_sign_in_ip, String
  key :sign_in_count, Integer
  key :remember_created_at, Time
  key :points, Integer
  key :sponsor, Boolean, default: false
  key :unsubscribe_all, Boolean, default: false
  key :unsubscribe_useful, Boolean, default: false

  validates :name, presence: true,
                   length: { minimum: 2 }
  validates :encrypted_password, presence: true,
                                 length: { minimum: 2 }
  validates :email, uniqueness: true, presence: true,
                    length: { minimum: 4 }
  validates :points, numericality: { only_integer: true }

  def self.from_omniauth(auth)
    user = where(email: auth.info.email).first

    # user.destroy can be used here for testing new users.

    if user.present?
    else
      user = User.new
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.image = auth.info.image
      user.points = 0
      user.skip_confirmation!
      user.save!
    end
    user
  end

  def add_points(new_points)
    @points = 0 unless defined?(@points)
    @points += new_points
    self.save!
  end

  def display
    if !defined?(@name)
      return ' '
    elsif defined?(@points)
    else
      @points = 0
      self.save!
    end
    return_value = "<table class='vcard'><tr><td align=center><img class='photo' src=#{image}></td><td>"
    return_value += "<table><tr><td class='fn'><a class='url' href=/users/#{id}>#{@name}</a></td></tr>"
    return_value += "<tr><td align=center>#{@points}"

    if @sponsor == true
      return_value += " <img src=http://votesquared.org/Halo.png width=12 height=12 alt='Sponsor Halo'>"
    end

    return_value += '</td></tr></table></td></table>'
    return_value
  end

  def admin?
    return true if id.to_s == ADMINS[id.to_s].to_s

    false
  end

  def already_following?(user, user_id)
    user.follows.each do |follow|
      return follow if follow.follower_id == user_id
    end
    false
  end
end

app/controllers/users_controller.rb
# Controller for users
class UsersController < ApplicationController
  def login
  end

  def new(auth)
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver!

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    sign_out
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_custom
    @user = User.find(params[:id])

    @user.sponsor = true?(params['users']['sponsor']) if current_user.admin?

    if current_user.admin? || current_user.id == @user.id
      @user.unsubscribe_all = true?(params['users']['unsubscribe_all'])
      @user.unsubscribe_useful = true?(params['users']['unsubscribe_useful'])
    end

    if @user.save!
      redirect_to @user
    else
      render 'edit'
    end
  end

  def true?(value)
    if value == 1.to_s
      return true
    else
      return false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<%= render :partial => "shared/top" %>

<h1>Congratulations, you have successfully signed out!  Want to do some more?</h1>
<p>
<center><%= link_to 'View Politicians', controller: 'politicians' %></center>
<p>
<%= render :partial => "shared/bottom" %>

app/views/users/edit.html.erb
<%= render "shared/top" %>
<h1><img src=<%= @user.image %> align=center> Editing <%= @user.name %>'s Profile</h1>

<%= form_for :users, method: :patch do |f| %>
  <% if current_user.admin? %>
    <%= f.label :sponsor %>
    <%= f.check_box :sponsor, {checked: @user.sponsor} %>
  <% end %>
  
  <h2>Email:</h2>
  <%= f.label :unsubscribe_all %>
  <%= f.check_box :unsubscribe_all, {checked: @user.unsubscribe_all} %><br>
  <%= f.label :unsubscribe_useful %>
  <%= f.check_box :unsubscribe_useful, {checked: @user.unsubscribe_useful} %>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= render "shared/bottom" %>

app/views/users/show.html.erb
<%= render "shared/top" %>
<title><%= @user.name %>'s Profile</title>
<% if user_signed_in? %>
  <% if current_user.admin? or current_user.id == @user.id %>
    <center><%= link_to 'Edit', edit_user_path(@user) %></center>
  <% end %>
<% end %>
<span class="vcard">
  <H1 class='fn'><%= @user.name %></H1> <img class='photo' src=<%= @user.image %>>
	<% if user_signed_in? && @user.already_following?(@user, current_user.id) %> 
	  <%= link_to(raw("<img src=/Unfollow.png alt='unfollow' align=right>"), user_follows_path(@user), :method => :create) %>
	<% else %>
	  <%= link_to(raw("<img src=/Follow.png alt='follow' align=right>"), user_follows_path(@user), :method => :create) %>
	<% end %>
	<p>
	  <strong>Points:</strong> <%= @user.points %>
	</p>
	<p>
	  <strong>Last Login:</strong> <%= @user.last_sign_in_at %>
	</p>
	<p>
	  <strong>Login Count:</strong> <%= @user.sign_in_count %>
	</p>
</span>
<strong>User's Ratings:</strong>
<table cellspacing=20 border=1>
  <% @user.voter_ratings.each do |voter_rating| %>
    <tr class='hreview'>
      <span style='visibility:hidden'><span class='reviewer'><%= @user.name %></span></span>
      <td align=center>
      <span class="item"><span class='fn'><%= voter_rating.politician_link.html_safe %></span></span> <br>
      <%= voter_rating.rating_html %>
    </td></tr>
  <% end %>
</table>

<center><a href="/">Home</a></center>

<%= render "shared/bottom" %>