config/routes.rb
VoteSquared::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :users do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
    resources :follows
    resources :voter_ratings
  end

  resources :politicians do
    resources :watches
    resources :voter_ratings do
      resources :votes
    end
  end

  resources :omniauth_callbacks, :devise

  match '/about/community' => 'about#community', via: [:get]
  match '/about/funding' => 'about#funding', via: [:get]
  match '/about/democratic_antipatterns' => 'about#democratic_antipatterns', via: [:get]
  match '/users/:id/edit', to: 'users#update_custom', via: [:patch]
  match '/politicians/:politician_id/voter_ratings/:id/edit', to: 'voter_ratings#update', via: [:patch]

  root 'welcome#index'
end

app/models/politician.rb
# Model for storing politicians.
class Politician
  include MongoMapper::Document
  include RatingsHtml

  many :voter_ratings
  many :watches

  # New fields need to be added to the controller, the form, and here.

  key :first_name, String
  key :last_name, String
  key :country, String
  key :state, String
  key :current_office, String
  key :candidate_for, String
  key :last_edit_user_id, ObjectId
  key :city, String
  key :county, String
  key :wikipedia_link, String
  key :campaign_link, String
  key :open_secrets_link, String
  key :official_link, String
  key :facebook, String
  key :google, String
  key :twitter, String

  validates :first_name, presence: true,
                         length: { minimum: 2 }
  validates :last_name, presence: true,
                        length: { minimum: 2 }
  validates :country, presence: true

  validates :last_edit_user_id, presence: true,
                                length: { minimum: 2 }
  validates :city, presence: true, if: :town_or_city_office?
  validates :county, presence: true, if: :county_office?

  def town_or_city_office?
    if is_office?('city')
      return true
    elsif is_office?('town')
      return true
    end

    false
  end

  def county_office?
    if is_office?('county')
      return true
    end

    false
  end

  def is_office?(office)
    if @current_office == 'N/A'
      return false
    elsif @current_office.length == 0
    elsif OFFICES[@country][@current_office]['level'] == office
      return true
    end

    if @candidate_for == 'N/A'
      return false
    elsif @candidate_for.length == 0
    elsif OFFICES[@country][@candidate_for]['level'] == office
      return true
    end

    false
  end

  def last_edit_user
    @user = User.find(@last_edit_user_id)
    if @user.nil?
      return ' '
    elsif defined?(@user)
      return @user.display
    else
      return ' '
    end
  end

  def has_social_links?
    if !defined?(@google)
      return false
    elsif !defined?(@facebook)
      return false
    elsif !defined?(@twitter)
      return false
    elsif @google.empty? && @facebook.empty? && @twitter.empty?
      return false
    end
    true
  end

  def sort_value
    if voter_ratings.none?
      return 0
    end

    avg = rating_avg
    avg * 100 + voter_ratings.count
  end

  def rating_avg
    if voter_ratings.none?
      return 0
    end

    total = 0

    voter_ratings.each do |voter_rating|
      total += voter_rating.rating
    end

    total.to_f / voter_ratings.count
  end

  def rating_stats_html
    if voter_ratings.none?
      return "(<span class='count'>0</span> ratings)".html_safe
    end

    avg = rating_avg

    fraction = avg.to_f - avg.to_i

    if fraction > 0.25 && fraction < 0.75
      half = true
    else
      half = false
    end

    if fraction > 0.75
      avg += 1
    end

    str = "<table><td valign=center><b class='rating'>" + rating_avg.to_s + '</b></td><td>'
    str += rating_hearts_html(avg, half)
    str += " (<span class='count'>" + voter_ratings.count.to_s
    str += '</span> ' + 'rating'.pluralize(voter_ratings.count) + ')</td></table>'

    str.html_safe
  end

  def full_name
    first_name + ' ' + last_name
  end

  def already_watching?(politician, user_id)
    politician.watches.each do |watch|
      if watch.watcher_id == user_id
        return watch
      end
    end
    false
  end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  def new
    @politician = Politician.new
  end

  def create
    @politician = Politician.new(politician_params)

    if @politician.save
      redirect_to @politician
      flash[:notice] = "Thank you, you've earned 10 points!"
      current_user.add_points(10)
    else
      render 'new'
    end
  end

  def edit
    @politician = Politician.find(params[:id])
  end

  def show
    @politician = Politician.find(params[:id])
  end

  def index
    @politicians = Politician.all
  end

  def update
    @politician = Politician.find(params[:id])

    if @politician.last_edit_user_id != current_user.id
      flash[:notice] = "Thank you, you've earned 1 point!"
      current_user.add_points(1)
    end

    if @politician.update_attributes(politician_params)
      redirect_to @politician
      recipients = []
      @politician.watches.each do |watch|
        send_mail(watch.watcher_id)
        recipients += [watch.watcher_id]
      end
      current_user.follows.each do |follow|
        send_mail(follow.follower_id) unless recipients.include?(follow.follower_id)
      end
    else
      render 'edit'
    end
  end

  def send_mail(user_id)
    user = User.find(user_id)
    unless user.unsubscribe_all
      UserMailer.watched_politician_update(@politician, user, current_user).deliver
    end
  end

  def destroy
    @politician = Politician.find(params[:id])
    @politician.destroy
    if @politician.last_edit_user_id == current_user.id
      flash[:notice] = "You've lost 10 points!"
      current_user.add_points(-10)
    end

    redirect_to politicians_path
  end

  # Private members

  private

  def politician_params
    params.require(:politician).permit(:first_name, :last_name, :country, :state, :current_office, :candidate_for, :last_edit_user_id, :voter_ratings, :city, :county, :wikipedia_link, :campaign_link, :open_secrets_link, :official_link, :facebook, :google, :twitter)
  end
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/views/politicians/_country.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Rating</th>
    <th>Country</th>
    <th>State</th>
    <th>Current Office</th>
    <th>Candidate For</th>
  </tr>
 
  <% row = 0 %>
  <% sorted_politicians = @politicians.sort! { |a,b| b.sort_value <=> a.sort_value } %>
  <% @politicians.each do |politician| %>
    <% if politician.country == country %>
      <% if (row += 1) % 2 == 0 %>
        <tr bgcolor=aquamarine>
      <% else %>
        <tr>
      <% end %>
      <td><%= link_to politician.full_name, politician_path(politician) %></td>
      <td><%= politician.rating_stats_html %></td>
      <td><%= politician.country %></td>
      <td><%= politician.state %></td>
      <td><%= politician.current_office %></td>
      <td><%= politician.candidate_for %></td>
        </tr>
    <% end %>
  <% end %>
</table>

<p><center>
<% if user_signed_in? %>
  <%= link_to 'New politician', new_politician_path %>
<% else %>
  <%= link_to('Login to Add a Politician', user_omniauth_authorize_path(:facebook))  %>
<% end %>
</center>

app/views/politicians/_form.html.erb
<%= form_for @politician do |f| %>
  
  <%# Error Logic: %>
  <% if @politician.errors.any? %>
  <div id="error_explanation">
    <font color=red>
    <h2><%= pluralize(@politician.errors.count, "error") %> prohibited
      this politician from being saved:</h2>
    <ul>
    <% @politician.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </font>
  </div>
  <% end %>
 
  <p class="field">
    <%= f.label :first_name %> <%= f.text_field :first_name %>
  </p>
 
  <p class="field">
    <%= f.label :last_name %> <%= f.text_field :last_name %>
  </p>
  
  <p>
    <%= f.label :country %><br>
    <%= f.select :country, OFFICES, {}, :onChange=>"switchCountry();" %>
  </p>
  
<script>
function switchCountry()
{
  var country = document.getElementById('politician_country').value;
	updateOffice(document.getElementById('politician_candidate_for'), country);
	updateOffice(document.getElementById('politician_current_office'), country);
	var select = document.getElementById('politician_state');
	removeOptions(select);
	if (country == "Canada") addCaProvinces(select);
	else addUSAStates(select);
}

function updateOffice(select, country)
{
  removeOptions(select);
  if (country == "Canada") addCaOffices(select);
	else addUSAOffices(select);
}

function addUSAOffices(select)
{
	<% OFFICES["United States of America"].each do |office| %>
	  var option = document.createElement("option");
	  option.text = '<%= office[0] %>';
	  option.value = '<%= office[0] %>';
	  select.add(option);
	<% end %>
}

function addCaOffices(select)
{
  <% OFFICES["Canada"].each do |office| %>
    var option = document.createElement("option");
    option.text = '<%= office[0] %>';
    option.value = '<%= office[0] %>';
    select.add(option);
  <% end %>
}

function addUSAStates(select)
{
  <% STATES.each do |state| %>
    var option = document.createElement("option");
    option.text = '<%= state[0] %>';
    option.value = '<%= state[0] %>';
    select.add(option);
  <% end %>
}

function addCaProvinces(select)
{
  <% PROVINCES.each do |province| %>
    var option = document.createElement("option");
    option.text = '<%= province[0] %>';
    select.add(option);
  <% end %>
}

function removeOptions(select)
{
	  for(var i=select.options.length-1; i>=0; i--)
	  {
	    select.remove(i);
	  }
}
</script>
  
  <p>
    <%= f.label :candidate_for %><br>
    <%= f.select :candidate_for, OFFICES["United States of America"].keys + OFFICES["Canada"].keys %>
  </p>
  
  <p>
    <%= f.label :current_office %><br>
    <%= f.select :current_office, OFFICES["United States of America"].keys + OFFICES["Canada"].keys %>
  </p>

  <p>
    <%= f.label :state %>/Province<br>
    <%= f.select :state,  STATES.keys + PROVINCES.keys %>
  </p>

  <p class="field">
    <%= f.label :county %> <%= f.text_field :county %>
  </p>
  
  <p class="field">
    <%= f.label :city %> <%= f.text_field :city %>
  </p>
  
  <h2>Links</h2>
  
  <p class="field">
    <b><%= f.label :wikipedia_link %>:</b><br>
    https://en.wikipedia.org/wiki/<%= f.text_field :wikipedia_link %>
  </p>
  
  <p class="field">
    <b><%= f.label :campaign_link %>:</b><br>
    <%= f.text_field :campaign_link %>
  </p>
  
  <p class="field">
    <b><%= f.label :open_secrets_link %>:</b><br>
    https://www.opensecrets.org/politicians/summary.php?cid=<%= f.text_field :open_secrets_link %>
  </p>
  
  <p class="field">
    <b><%= f.label :official_link %>:</b><br>
    <%= f.text_field :official_link %>
  </p>
  
  <h2>Social Media</h2>
  
  <p class="field">
    <b><%= f.label :facebook %>:</b><br>
    https://www.facebook.com/<%= f.text_field :facebook %>
  </p>
  
  <p class="field">
    <b><%= f.label :google %>+ ID:</b><br>
    https://plus.google.com/<%= f.text_field :google %>/posts
  </p>
  
  <p class="field">
    <b><%= f.label :twitter %> account:</b><br>
    https://twitter.com/<%= f.text_field :twitter %>
  </p>
  
  
  <%= f.hidden_field :last_edit_user_id, :value => current_user.id %>
  
  <% if user_signed_in? %>    
    <p>
      <%= f.submit %>
    </p>
  <% end %>
  
<% end %>

app/views/politicians/_show_body.html.erb
<title><%= @politician.first_name %> <%= @politician.last_name %>'s Ratings</title>

<span class="vcard">
  <H1 align=center class='item'>
    <span class='fn'>
      <span class="given-name"><%= @politician.first_name %></span> 
      <span class="family-name"><%= @politician.last_name %></span></span>'s Ratings
    <% if user_signed_in? && @politician.already_watching?(@politician, current_user.id) %> 
      <%= link_to(raw("<img src=/Unwatch.png alt='unwatch' align=right>"), politician_watches_path(@politician), :method => :create) %>
    <% else %>
      <%= link_to(raw("<img src=/Watch.png alt='watch' align=right>"), politician_watches_path(@politician), :method => :create) %>
    <% end %>
  </H1>

  <%= render "show_body_table" %>
</span>

<center>
  <table cellspacing=10><tr>
    <td>
	  <%= link_to 'Back', politicians_path %> 
	</td>
	  <% if user_signed_in? %>
	    <td id='rating_link' style="display:none">
	      <a href="#add_rating">Add Rating</a> 
	    </td>
	    <% if current_user.points > 2 %>
	      <td>
	        <%= link_to 'Edit', edit_politician_path(@politician) %> 
	      </td>
	    <% end %>
	    <% if defined?(current_user.points) && ! current_user.points.nil? %>  
	      <% if current_user.points > 20 %>
	        <td>
	          <%= link_to 'Delete', politician_path(@politician), method: :delete, data: { confirm: "Are you sure #{current_user.name}?  This cannot be undone and will cost you 10 points!  If this is a real politician please leave them!" } %>
	        </td>
	      <% end %>
	    <% end %>
	  <% else %>
	    <td>
	      <%= link_to('Login to Rate or Edit', user_omniauth_authorize_path(:facebook))  %>
	    </td>
	  <% end %>
  </tr></table>
</center>

app/views/politicians/_show_body_table.html.erb
<% if @politician.voter_ratings.any? %>
  <center>
    <%= @politician.rating_stats_html %>
  </center>
<% end %>

<table align=center><tr cellspacing=20><td>
<% if @politician.has_social_links? %>
  <table>
    <th colspan=3>
        <% if ! @politician.facebook.empty? %>
          <img class='photo' src=http://graph.facebook.com/<%= @politician.facebook %>/picture?type=square><br>
      <% end %>
      Social Links
    </th>
    <tr>
    <% if ! @politician.facebook.empty? %>
      <td>
        <a href=https://www.facebook.com/<%= @politician.facebook %>><img alt="facebook" src=http://VoteSquared.org/fb-logo.png></a>
      </td>
    <% end %>

    <% if ! @politician.google.empty? %>
      <td>
        <a href=https://plus.google.com/<%= @politician.google %>/posts><img alt="Google+" src=http://VoteSquared.org/g+-logo.png></a>
      </td>
    <% end %>
  
    <% if ! @politician.twitter.empty? %>
      <td>
        <a href=https://twitter.com/<%= @politician.twitter %>><img alt="Twitter" src=http://VoteSquared.org/twitter-logo.png></a>
      </td>
    <% end %>
    </tr>
  </table>
<% end %>

</td>

<!--  Second Table Column     -->

<td>
<% if ! defined?(@politician.wikipedia_link.empty?) %> 
<% elsif ! @politician.wikipedia_link.empty? %>
  <p>
    <center><strong><a href=https://en.wikipedia.org/wiki/<%= @politician.wikipedia_link %>>Wikipedia Page</a></strong></center>
  </p>
<% end %>

<% if ! defined?(@politician.campaign_link.empty?) %> 
<% elsif ! @politician.campaign_link.empty? %>
  <p>
    <center><strong>Campaign Page: <a class='url' href=<%= @politician.campaign_link %>><%= @politician.campaign_link %></a></strong></center>
  </p>
<% end %>
<% if ! defined?(@politician.open_secrets_link.empty?) %> 
<% elsif ! @politician.open_secrets_link.empty? %>
  <p>
    <center><strong><a href=https://www.opensecrets.org/politicians/summary.php?cid=<%= @politician.open_secrets_link %>>Open Secrets Page</a></strong></center>
  </p>
<% end %>

<% if ! defined?(@politician.wikipedia_link.empty?) %> 
<% elsif ! @politician.wikipedia_link.empty? %>
  <p>
    <strong>Official Page: <a href=<%= @politician.official_link %>><%= @politician.official_link %></a></strong>
  </p>
<% end %> 

<p>
  <strong>Country:</strong>
  <span class="country-name"><%= @politician.country %></span>
  
  <strong>State/Province:</strong>
  <abbr class='region'><%= @politician.state %></abbr>
  
  <% if defined?(@politician.county.length) %>
    <% if @politician.county.length > 0 %>
      <strong>County:</strong>
      <%= @politician.county %>
    <% end %>
  <% end %>
  
  <% if defined?(@politician.city.length) %>
    <% if @politician.city.length > 0 %>
      <strong>City:</strong>
      <span class='locality'><%= @politician.city %></span>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Current Office:</strong>
  <span class='category'><%= @politician.current_office %></span>
</p>

<p>
  <strong>Candidate For:</strong>
  <%= @politician.candidate_for %>
</p>

<p>
  <table><td><strong>Last Edit by:</strong></td>
  <td><span itemprop="author" itemscope itemtype="http://schema.org/Person"><%= @politician.last_edit_user.html_safe %></span></td></table>
</p>
</td></tr></table>

app/views/politicians/edit.html.erb
<%= render "shared/top" %>
<title>Editing Politician</title>
<h1>Editing Politician</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', politicians_path %>
<%= render "shared/bottom" %>

app/views/politicians/index.html.erb
<%= render "shared/top" %>
<title>Politician Listing</title>
<h1>Listing politicians</h1>

  <input type="radio" id="send_poll" name="country" value="USA" />USA      
  <input type="radio" id="send_poll" name="country" value="Canada" />Canada<br/>

<script>
$(document).ready(function(){

    $("#USA").hide();
    $("#Canada").hide();

    $("input:radio[name='country']").change(function(){  

            if(this.value == 'USA' && this.checked){
              $("#USA").show();
              $("#Canada").hide();
            }
            else if(this.value == 'Canada' && this.checked){
                $("#Canada").show();
                $("#USA").hide();
            }

    });

});
</script>
 
<div id='USA' style='display:none'>
  <%= render 'country', :country => 'United States of America' %>
</div>
<div id='Canada' style='display:none'>
  <%= render 'country', :country => 'Canada' %>
</div>

<%= render 'shared/bottom' %>

app/views/politicians/new.html.erb
<%= render "shared/top" %>
<title>New Politician</title>
<h1>New Politician</h1>

<%= render 'form' %>

<%= link_to 'Back', politicians_path %>

<%= render "shared/bottom" %>

app/views/politicians/show.html.erb
<%= render "shared/top" %>

<% if ! defined?(@politician.first_name) %>
  <title>Nothing to see here!</title>
  <H1>This is not the politician you are looking for.  They must have performed a Jedi mind trick!</H1>
  <p>Try heading back to the <%= link_to 'list of politicians', politicians_path %>!</p>
<% else %>
  <span class="hreview-aggregate">
    <%= render "show_body" %>
  </span>
  <%= render "voter_ratings/show" %>
<% end %>
<p>

<center><%= link_to 'Back', politicians_path %></center>

<%= render "shared/bottom" %>